apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    version: 4.7.1
    includeCRDs: true
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      fullnameOverride: ingress-nginx
      controller:
        publishService:
          enabled: true
        extraArgs:
          enable-ssl-passthrough: true
