apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress
helmCharts:
  - name: nginx-ingress-controller
    releaseName: nginx-ingress-controller
    version: 9.7.5
    includeCRDs: true
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      fullnameOverride: nginx-ingress-controller
      publishService:
        enabled: true
      defaultBackend:
        extraArgs:
          enable-ssl-passthrough: true
