apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: promtail
    includeCRDs: true
    releaseName: promtail
    version: 6.7.4
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      fullnameOverride: promtail
      config:
        clients:
          - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
            # tenant_id: default # required if loki is run in multi-tenant mode
      loki:
        serviceName: ""
      daemonset:
        enabled: true
