apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jaeger-cassandra
  namespace: observability
spec:
  encryptedData:
    cassandra-password: AgAqZP3Nu8wc06hCtTmFWIGE1ezh/cp8pTOs0L3xOvAjfHXYfi5kvY6mtprGhuo0Xe8yAli6syZSHfLCDvjleBA7exZeIwEMukijTJ2+HFsgHu5qcYLKUHzoxCIFXPVBSjdrOQtSIZ6HanJ/r6AdtllhVaelSVVv6VUNvhfHiZc9IFH9NyWLqQfdmAdh6Jx+9faUUITbTBpJREysfUcwiT8eu7n3uOU2b6c+uqM0ZM7wUQarvLOyfurpUy7D4bSUO03lkWJNgvPm7TE1Sb6yAh0OvUSmMKhr8PKooWj/rrZrXNdqsAVzebvIWSgg5VP3KD73RQHNFxiGpRNa2YQLZMtoSiNEd7tqZ9QNMEdJUaXntUNsImO7CFonqkBRUacGEAjleWW167bX7IZOeIWCfpK/3ckRCnA6GqWkOJRzK05S6XbokX0Vd0iLFMcvIYWZKFx+3k7bKZ0+y3DUAC393IgwXMrt/wbguhPM6nFzUH6oUQMX3vM8byj4DC+UMsn+my9X5tfBfP/K/wkEFFbUp3FWwJpUAR0VNNRAYiRX77FrSuYgT8zXG9d6aELESuszvTmylKMXOj93LgEKJQIyYy7CowsrSWqyRHHJwpjGsEt/rvMJl0jSez0CykcfJxEuDTX2ilUoO+FHfyB7ba/Eo2hIwzwTFgaLiq4/+Ko3zgrfu5KWXciuUdOxqzQ2ueF8Ijpwj2ccuXGKFaWOQkAZN76yDNQBVThM7FIrlvdEuc8Yow==
  template:
    metadata:
      creationTimestamp: null
      name: jaeger-cassandra
      namespace: observability

