apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - ../../base
  - virtual-service.yaml
helmCharts:
  - name: hajimari
    releaseName: hajimari
    version: 2.0.2
    repo: https://hajimari.io
    valuesInline:
      hajimari:
        name: "cluster"
        defaultEnable: true
      service:
        main:
          ports:
            http:
              port: 3000
      ingress:
        main:
          enabled: false
          hosts:
            - host: cluster.sciops.net
