apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: homepage
  namespace: homepage
  annotations:
    link.argocd.argoproj.io/external-link: https://unset-127-0-0-1.nip.io # kpt-set: https://${host}
spec:
  hosts:
    - "unset-127-0-0-1.nip.io" # kpt-set: ${host}
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: hajimari.homepage.svc.cluster.local
            port:
              number: 3000
