---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: homepage
  namespace: homepage
  annotations:
    link.argocd.argoproj.io/external-link: https://cluster.sciops.net
spec:
  hosts:
    - "cluster.sciops.net"
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - uri: 
            prefix: /
      route:
        - destination:
            host: hajimari.homepage.svc.cluster.local
            port:
              number: 3000
