apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: grafana
    includeCRDs: true
    releaseName: grafana
    version: 6.57.2
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      fullnameOverride: grafana
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      grafana.ini:
        server:
          domain: grafana.cluster.sciops.net
      admin:
        existingSecret: "grafana-secrets"
        userKey: GF_SECURITY_ADMIN_USER
        passwordKey: GF_SECURITY_ADMIN_PASSWORD
      persistence:
        type: pvc
        enabled: true
      envValueFrom:
        GF_AUTH_GITHUB_CLIENT_ID:
          secretKeyRef:
            name: grafana-secrets
            key: GF_AUTH_GITHUB_CLIENT_ID
        GF_AUTH_GITHUB_CLIENT_SECRET:
          secretKeyRef:
            name: grafana-secrets
            key: GF_AUTH_GITHUB_CLIENT_SECRET
      env:
        GF_SERVER_DOMAIN: grafana.cluster.sciops.net
        GF_SERVER_ROOT_URL: "https://grafana.cluster.sciops.net"
        GF_AUTH_GITHUB_ENABLED: true
        GF_AUTH_GITHUB_ALLOW_SIGN_UP: true
        GF_AUTH_GITHUB_SCOPES: "user:email,read:org"
        GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: sciops
        GF_AUTO_ASSIGN_ORG_ROLE: Admin

      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Alertmanager
              type: alertmanager
              url: http://prometheus-alertmanager
              uid: alertmanager
              access: proxy
              jsonData:
                implementation: prometheus
            - name: Loki
              uid: loki
              type: loki
              access: proxy
              url: http://loki-query-frontend:3100
              version: 1
              jsonData:
                alertmanagerUid: alertmanager
                maxLines: 5000
                timeout: "60"
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server
              access: proxy
              isDefault: true
              jsonData:
                manageAlerts: true
                alertmanagerUid: alertmanager
            - name: Jaeger
              uid: jaeger
              type: jaeger
              access: proxy
              url: http://jaeger-query.observability:16686
              version: 1
      notifiers:
        notifiers.yaml:
          notifiers:
            - name: prometheus-alertmanager
              type: prometheus-alertmanager
              uid: prometheus-alertmanager
              org_id: 1
              is_default: true
              settings:
                url: http://prometheus-alertmanager
          delete_notifiers: []

      sidecar:
        plugins:
          enabled: true
        notifiers:
          enabled: false
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          folder: /var/lib/grafana/dashboards/external
          folderAnnotation: grafana.cluster.sciops.net/dashboard-folder
          #      searchNamespace: ALL
          provider:
            disableDelete: false
            allowUiUpdates: true
            foldersFromFilesStructure: true
        datasources:
          enabled: false
          label: grafana_datasource
          labelValue: "1"

      plugins:
        - grafana-github-datasource
        - grafana-piechart-panel

      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: "Kubernetes Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
            - name: "alertmanager"
              orgId: 1
              folder: "Alertmanager Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/alertmanager
            - name: "argocd"
              orgId: 1
              folder: "ArgoCD Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/argocd
            - name: "github"
              orgId: 1
              folder: "GitHub Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/github
            - name: "istio"
              orgId: 1
              folder: "Istio Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/istio
            - name: "loki"
              orgId: 1
              folder: "Loki Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/loki
            - name: "jaeger"
              orgId: 1
              folder: "Jaeger Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/jaeger
            - name: "cert-manager"
              orgId: 1
              folder: "Cert-Manager Dashboards"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/jaeger
      dashboards:
        default:
          golang-metrics:
            datasource: Prometheus
            gnetId: 13240
        alertmanager:
          alertmanager-grafana-dashboard:
            datasource: Prometheus
            gnetId: 9578
        argocd: {}
        github: {}
        istio:
          istio-performance-dashboard:
            datasource: Prometheus
            gnetId: 12153
        loki:
          loki-stack-monitoring:
            datasource: Loki
            gnetId: 14055
          loki-istio-service:
            datasource: Loki
            gnetId: 14876
            revision: 3
          loki-container-log:
            datasource: Loki
            gnetId: 16966
        jaeger:
          jaeger:
            datasource: Prometheus
            gnetId: 10001
        cert-manager: {}
