apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-kf2
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster-kf2
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster-kf2
      syncer:
        extraArgs:
          - --tls-san="kf2.k.cluster.sciops.net"
          - --out-kube-config-server="https://kf2.k.cluster.sciops.net"
        kubeConfigContextName: "vcluster-kf2"
      storage:
        persistence: true
      sync:
        hoststorageclasses:
          enabled: true
      # fallbackHostDns: true
      # plugin:
      #   cert-manager-plugin:
      #     image: ghcr.io/loft-sh/vcluster-plugins/cert-manager-plugin:0.3.0
      #     imagePullPolicy: IfNotPresent
      #     rbac:
      #       role:
      #         extraRules:
      #           - apiGroups: ["cert-manager.io"]
      #             resources: ["issuers", "certificates"]
      #             verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
      #       clusterRole:
      #         extraRules:
      #           - apiGroups: ["apiextensions.k8s.io"]
      #             resources: ["customresourcedefinitions"]
      #             verbs: ["get", "list", "watch"]
