apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    link.argocd.argoproj.io/external-link: https://grafana.unset-127-0-0-1.nip.io # kpt-set: https://grafana.${host}
spec:
  hosts:
    - "grafana.unset-127-0-0-1.nip.io" # kpt-set: grafana.${host}
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: grafana.monitoring.svc.cluster.local
