apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- loki-gcs-bucket.yaml
helmCharts:
  - name: loki
    includeCRDs: true
    releaseName: loki
    namespace: monitoring
    version: 5.8.0
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      nameOverride: loki
      labels:
        app: loki
      global:
        lokiGcsBucket: 
          name: loki-gcs-bucket
          key: bucket_name
      loki:
        distributorLabels:
          app: loki
        storageConfig:
          aws:
            s3: false  
          gcs:
            bucketnames: $(datadir .Values.global.lokiGcsBucket)
          type: gcs
        gateway:
          enabled: false
      memberlist:
        service:
          publishNotReadyAddresses: true
