apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: loki-distributed
    includeCRDs: true
    releaseName: loki
    namespace: monitoring
    version: 0.70.0
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      nameOverride: loki
      labels:
        app: loki
      global: {}
      loki:
        appProtocol: tcp
      queryFrontend:
        appProtocol:
          grpc: tcp
      querier:
        appProtocol:
          grpc: tcp
      ingester:
        appProtocol:
          grpc: tcp
      distributor:
        appProtocol:
          grpc: tcp
