apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- loki-gcs-bucket.yaml
helmCharts:
  - name: loki
    includeCRDs: true
    releaseName: loki
    namespace: monitoring
    version: 5.8.11
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      nameOverride: loki
      labels:
        app: loki
      global:
        lokiGcsBucket: 
          name: loki-gcs-bucket
          key: bucket_name
      loki:
        # clusterDomain: ""
        auth_enabled: false
        distributorLabels:
          app: loki
        storageConfig:
          # aws:
          #   s3: false  
          type: gcs
          gcs:
            bucketnames: $(datadir .Values.global.lokiGcsBucket)
        gateway:
          enabled: false
      queryFrontend:
        service:
          ports:
            grpc:
              name: grpclb
              appProtocol: tcp
      querier:
        service:
          ports:
            grpc:
              appProtocol: tcp
      ingester:
        enabled: true
        service:
          type: ClusterIP
          headless:
            enabled: true
          ports:
            grpc:
              appProtocol: tcp
      distributor:  
        service:
          ports:
            grpc:
              appProtocol: tcp
      memberlist:
        service:
          ports:
            http: 
              appProtocol: tcp
          publishNotReadyAddresses: true
      write:
        persistence:
          enableStatefulSetAutoDeletePVC: false
      read:
        persistence:
          enableStatefulSetAutoDeletePVC: false
      backend:
        persistence:
          enableStatefulSetAutoDeletePVC: false
      # singleBinary:
      #   persistence:
      #     enableStatefulSetAutoDeletePVC: false
