apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loft
helmCharts:
  - name: loft
    includeCRDs: true
    releaseName: loft
    version: 3.2.0
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: loft
      envValueFrom:
        CLIENT_ID:
          secretKeyRef:
            name: github-secrets
            key: client-id
        CLIENT_SECRET:
          secretKeyRef:
            name: github-secrets
            key: client-secret
      config:
        loftHost: https://loft.cluster.sciops.net
        audit:
            enabled: true
        auth:
          password:
            disable: true
          github:
            clientId: $CLIENT_ID
            clientSecret: $CLIENT_SECRET
            redirectURI: https://loft.cluster.sciops.net/auth/github/callback
            orgs:
              name: UNSET_ORG # kpt-set: ${github_org}
              teams:
                - platform
