apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-dev
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster-dev
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster-dev
      syncer:
        extraArgs:
          - --tls-san="dev.k.cluster.sciops.net"
          - --out-kube-config-server="https://dev.k.cluster.sciops.net"
        kubeConfigContextName: "vcluster-dev"
      storage:
        persistence: true
      fallbackHostDns: true
