apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-dev
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster-dev
    version: 0.15.5
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster-dev
      syncer:
        extraArgs:
          - --tls-san="dev.k.unset-127-0-0-1.nip.io" # kpt-set: --tls-san="dev.k.${host}"
          - --out-kube-config-server="https://dev.k.unset-127-0-0-1.nip.io" # kpt-set: --out-kube-config-server="https://dev.k.${host}"
        kubeConfigContextName: "vcluster-dev"
      storage:
        persistence: true
      fallbackHostDns: true
      sync:
        hoststorageclasses:
          enabled: true
