apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-kf
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster
      syncer:
        extraArgs:
          - --tls-san="kf.k.cluster.sciops.net"
          - --out-kube-config-server="https://kf.k.cluster.sciops.net"
        kubeConfigContextName: "vcluster-kf"
      storage:
        persistence: true
      fallbackHostDns: true
      sync:
        persistentvolumes:
          enabled: true