apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-kf
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster-kf
    version: 0.20.1
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster-kf
      syncer:
        extraArgs:
          - --tls-san="kf.k.unset-127-0-0-1.nip.io" # kpt-set: --tls-san="kf.k.${host}"
          - --out-kube-config-server="https://kf.k.unset-127-0-0-1.nip.io" # kpt-set: --out-kube-config-server="https://kf.k.${host}"
        kubeConfigContextName: "vcluster-kf"
      storage:
        persistence: true
      sync:
        hoststorageclasses:
          enabled: true
      fallbackHostDns: true
      plugin:
        cert-manager-plugin:
          image: ghcr.io/loft-sh/vcluster-plugins/cert-manager-plugin:0.3.0
          imagePullPolicy: IfNotPresent
          rbac:
            role:
              extraRules:
                - apiGroups: ["cert-manager.io"]
                  resources: ["issuers", "certificates"]
                  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
            clusterRole:
              extraRules:
                - apiGroups: ["apiextensions.k8s.io"]
                  resources: ["customresourcedefinitions"]
                  verbs: ["get", "list", "watch"]
