apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ns.yaml
commonLabels:
  app: jaeger-operator
  version: 2.46.2
helmCharts:
  - name: jaeger-operator
    releaseName: jaegertracing
    version: 2.46.2
    repo: https://jaegertracing.github.io/helm-charts
    includeCRDs: true
    namespace: observability
    valuesInline:
      fullnameOverride: jaeger-operator
      rbac:
        create: true
        clusterRole: true

  - name: jaeger
    releaseName: jaeger
    version: 0.71.10
    repo: https://jaegertracing.github.io/helm-charts
    namespace: observability
    valuesInline:
      commonLabels:
        app: jaeger
        version: 1.45.0
      cassandra:
        enabled: true
        # clusterDomain: cluster.local # defaults to cluster.local
        dbUser:
          existingSecret: jaeger-cassandra
      query:
        extraEnvVars:
          - name: METRICS_STORAGE_TYPE
            value: prometheus
          - name: PROMETHEUS_SERVER_URL
            value: http://prometheus-server.monitoring.svc.cluster.local
          - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
            value: "true"
