apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: vcluster
spec:
  containers:
  - name: debug-container
    image: alpine:latest
    command: ["sleep", "3600"]

# apiVersion: v1
# kind: Pod
# metadata:
#   name: dev
#   namespace: vcluster # check
# spec:
#   containers:
#   - name: dev
#     image: docker.io/library/ubuntu:mantic-20230624
#     command: ["sleep", "infinity"]
#     volumeMounts:
#     - mountPath: /mnt
#       name: testvolume
#   volumes:
#   - name: testvolume
#     persistentVolumeClaim:
#       claimName: claim-data # check
