apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: dex
spec:
  hosts:
    - "dex.unset-127-0-0-1.nip.io" # kpt-set: dex.${host}
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - headers:
        request:
          set:
            X-Forwarded-Port: "443"
      route:
        - destination:
            port:
              number: 5556
            host: dex.dex.svc.cluster.local
