apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-deploykf
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster-deploykf
      syncer:
        extraArgs:
          - --tls-san="k8s-deploykf.cluster.sciops.net"
          - --out-kube-config-server="https://k8s-deploykf.cluster.sciops.net"
        kubeConfigContextName: "vcluster-deploykf"
      storage:
        persistence: true
      fallbackHostDns: true
