apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-deploykf
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster-deploykf
      service:
        type: ClusterIP
      syncer:
        extraArgs:
          - --tls-san="deploykf.cluster.sciops.net"
          - --out-kube-config-server="https://deploykf.cluster.sciops.net"
        kubeConfigContextName: "vcluster"
      storage:
        persistence: false
      ingress:
        enabled: true
        ingressClassName: "nginx"
        host: "deploykf.cluster.sciops.net"
        rules:
        - host: "deploykf.cluster.sciops.net"
          http:
            paths:
            - backend:
                service:
                  name: vcluster
                  port: 
                    number: 443
              path: /
              pathType: ImplementationSpecific
