apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
  - ns.yaml
helmCharts:
  - name: dex
    releaseName: dex
    version: 0.13.0
    repo: https://charts.dexidp.io
    valuesInline:
      image:
        tag: v2.35.3
      envVars:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-client
              key: client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-client
              key: client-secret
        - name: JAEGER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-client
              key: jaeger-secret
        - name: KIALI_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-client
              key: kiali-secret
      config:
        issuer: https://dex.cluster.sciops.net
        storage:
          type: memory
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $GITHUB_CLIENT_ID
              clientSecret: $GITHUB_CLIENT_SECRET
              redirectURI: https://dex.cluster.sciops.net/callback
              orgs:
                - name: UNSET_ORG # kpt-set: ${github_org}
                  teams:
                    - platform
              loadAllGroups: false
              teamNameField: slug
              useLoginAsID: false
        oauth2:
          skipApprovalScreen: true
        staticClients:
          - id: example-app
            name: "Example App"
            redirectURIs:
              - "http://127.0.0.1:5555/callback"
            secret: ZXhhbXBsZS1hcHAtc2VjcmV0

          - id: jaeger-query
            name: "Jaeger"
            redirectURIs:
              - "https://jaeger.cluster.sciops.net/oauth2/callback"
            SecretEnv: JAEGER_CLIENT_SECRET

          - id: kiali-client
            name: "Kiali"
            redirectURIs:
              - "https://kiali.cluster.sciops.net/kiali"
            SecretEnv: KIALI_CLIENT_SECRET
