apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - "prometheus.unset-127-0-0-1.nip.io" # kpt-set: prometheus.${host}
              - "kiali.unset-127-0-0-1.nip.io" # kpt-set: kiali.${host}
              - "jaeger.unset-127-0-0-1.nip.io" # kpt-set: jaeger.${host}
              - "argocd.unset-127-0-0-1.nip.io" # kpt-set: argocd.${host}
              - "grafana.unset-127-0-0-1.nip.io" # kpt-set: grafana.${host}
              - "unset-127-0-0-1.nip.io" # kpt-set: ${host}
      when:
        - key: request.headers[x-envoy-external-address]
          values:
            - "192.168.1.1"
    - to:
        - operation:
            hosts:
              - "unset-127-0-0-1.nip.io" # kpt-set: ${host}
              - "dex.unset-127-0-0-1.nip.io" # kpt-set: dex.${host}
              - "argocd.unset-127-0-0-1.nip.io" # kpt-set: argocd.${host}
