apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unset-127-0-0-1.nip.io # kpt-set: ${host}
spec:
  commonName: unset-127-0-0-1.nip.io # kpt-set: ${host}
  dnsNames:
    - unset-127-0-0-1.nip.io # kpt-set: ${host}
    - "*.unset-127-0-0-1.nip.io" # kpt-set: *.${host}
  issuerRef:
    kind: ClusterIssuer
    name: unset-127-0-0-1.nip.io # kpt-set: ${host}
  secretName: unset-127-0-0-1.nip.io # kpt-set: ${host}
