apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: certs
  name: cluster.sciops.net
spec:
  acme:
    email: user@email.com # kpt-set: ${cluster_issuer_email}
    privateKeySecretRef:
      name: issuer-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudDNS:
            project: UNSET_PROJECT # kpt-set: ${cloud_project_id}
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
