apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: certs
  name: cluster.sciops.net
spec:
  acme:
    email: smithcam@broadinstitute.org
    privateKeySecretRef:
      name: issuer-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudDNS:
            project: sciexp-111111
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   labels:
#     app.kubernetes.io/instance: certs
#   name: hostname.net
# spec:
#   acme:
#     email: user@email.com
#     privateKeySecretRef:
#       name: issuer-key
#     server: https://acme-v02.api.letsencrypt.org/directory
#     solvers:
#       - selector:
#           dnsZones:
#             - hostname.net
#         dns01:
#           route53:
#             region: us-east-1
