apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app_label: istio-ingressgateway
    app.kubernetes.io/version: 1.18.0
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "prometheus.unset-127-0-0-1.nip.io" # kpt-set: prometheus.${host}
        - "kiali.unset-127-0-0-1.nip.io" # kpt-set: kiali.${host}
        - "jaeger.unset-127-0-0-1.nip.io" # kpt-set: jaeger.${host}
        - "dex.unset-127-0-0-1.nip.io" # kpt-set: dex.${host}
        - "argocd.unset-127-0-0-1.nip.io" # kpt-set: argocd.${host}
        - "grafana.unset-127-0-0-1.nip.io" # kpt-set: grafana.${host}
        - "unset-127-0-0-1.nip.io" # kpt-set: ${host}
    - port:
        name: https-cluster
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: unset-127-0-0-1.nip.io # kpt-set: ${host}
      hosts:
        - "prometheus.unset-127-0-0-1.nip.io" # kpt-set: prometheus.${host}
        - "kiali.unset-127-0-0-1.nip.io" # kpt-set: kiali.${host}
        - "jaeger.unset-127-0-0-1.nip.io" # kpt-set: jaeger.${host}
        - "dex.unset-127-0-0-1.nip.io" # kpt-set: dex.${host}
        - "argocd.unset-127-0-0-1.nip.io" # kpt-set: argocd.${host}
        - "grafana.unset-127-0-0-1.nip.io" # kpt-set: grafana.${host}
        - "unset-127-0-0-1.nip.io" # kpt-set: ${host}
