apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-ora
helmCharts:
  - name: vcluster
    includeCRDs: true
    releaseName: vcluster
    version: 0.15.2
    repo: https://charts.loft.sh
    valuesInline:
      fullnameOverride: vcluster
      syncer:
        extraArgs:
          - --tls-san="ora.k.cluster.sciops.net"
          - --out-kube-config-server="https://ora.k.cluster.sciops.net"
        kubeConfigContextName: "vcluster-ora"
      storage:
        persistence: true
      fallbackHostDns: true
      sync:
        hoststorageclasses:
          enabled: true
      plugin:
        cert-manager-plugin:
          image: ghcr.io/loft-sh/vcluster-plugins/cert-manager-plugin:0.3.0
          imagePullPolicy: IfNotPresent
